# Generated by Django 4.1.3 on 2023-10-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(choices=[("M", "M"), ("F", "F")], max_length=20),
        ),
    ]
