# Generated by Django 4.1.5 on 2023-01-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_gym"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
