# Generated by Django 4.1.3 on 2023-10-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_patient_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="dateOfBirth",
            field=models.DateField(null=True),
        ),
    ]
