# Generated by Django 4.1.3 on 2023-10-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_patient_dateofbirth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "M"), ("F", "F")], default="", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_no",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
