# Generated by Django 4.1.5 on 2023-01-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_gym_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gym",
            old_name="approved",
            new_name="status",
        ),
    ]
