# Generated by Django 4.1.3 on 2023-10-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_patient_gender_alter_patient_phone_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="dateOfBirth",
            new_name="dob",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="user_profile",
        ),
        migrations.AddField(
            model_name="patient",
            name="address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="first_name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="username",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "M"), ("F", "F")], default="", max_length=20, null=True
            ),
        ),
    ]
