# Generated by Django 4.1.3 on 2023-10-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_dateofbirth_patient_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="dob",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "M"), ("F", "F")], default="", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_no",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="patient",
            name="username",
            field=models.CharField(max_length=20),
        ),
    ]
