# Generated by Django 4.1.3 on 2023-10-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_patient_address_alter_patient_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="dob",
            field=models.DateField(null=True),
        ),
    ]
