# Generated by Django 4.1.3 on 2023-10-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_patient_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
