# Generated by Django 4.1.3 on 2023-10-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_room_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("drug_prescription", models.TextField()),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "patient_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.patient"
                    ),
                ),
            ],
        ),
    ]
