# Generated by Django 4.1.3 on 2023-10-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_medication"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomOccupancies",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("book_number", models.IntegerField(unique=True)),
                ("date_in", models.DateField()),
                ("date_out", models.DateField()),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.patient"
                    ),
                ),
                (
                    "room_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.room"
                    ),
                ),
            ],
        ),
    ]
