# Generated by Django 4.1.3 on 2023-10-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_roomoccupancies"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomoccupancies",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roomoccupancies",
            name="paid_staff",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.staff"
            ),
        ),
    ]
