# Generated by Django 4.1.3 on 2023-10-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_roomoccupancies_paid_roomoccupancies_paid_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="patient_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.patient"
            ),
        ),
    ]
