# Generated by Django 4.1.3 on 2023-10-18 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_medication_patient_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomoccupancies",
            name="paid_staff",
        ),
        migrations.AddField(
            model_name="patient",
            name="staff",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.staff"
            ),
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("status", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.patient"
                    ),
                ),
            ],
        ),
    ]
