# Generated by Django 4.1.3 on 2023-10-18 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_medication_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.staff"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.staff"
            ),
        ),
    ]
