# Generated by Django 4.1.3 on 2023-10-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_medication_staff_alter_patient_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomoccupancies",
            name="staff_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.staff"
            ),
        ),
    ]
