# Generated by Django 4.1.3 on 2023-10-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_roomoccupancies_staff_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomoccupancies",
            old_name="paid",
            new_name="paid_staff",
        ),
    ]
