# Generated by Django 4.1.3 on 2023-10-18 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_rename_paid_staff_roomoccupancies_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="patient_id",
        ),
        migrations.AddField(
            model_name="billing",
            name="occupant_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.roomoccupancies",
            ),
        ),
    ]
